### ISSUE TITLE
Use docker to protect system while executing commands

### ISSUE THREAD

**Issue by igormcoelho** [shoeffner/pandoc-source-exec#14]
One thing that bothers me (a lot!) is security issues regarding code execution...
Someone could do something really bad (by mistake perhaps) just by passing a wrong command in `cmd` parameter.
One alternative is to have users executing commands inside a docker instance (they can use `cmd` for that).

But I wonder if something like this shouldn't be default (and add docker as dependency). What do you think about it @shoeffner ?

I think this is precisely why pandoc would prevent giving such "power" by default... maybe if docker is assumed (by default) here, it would make it possible for pandoc to have this filter as "official"... just a few thoughts. And if it goes in this direction, one useful parameter could be a list of "output files" (besides the natural stdout), and docker container could limit the volume to only that specified files, or current directory, as this would already block some other security issues due to "important system files" being overwritten or deleted.

**Comment by shoeffner** [comment]
Adding docker as a dependency to run every conceivable command feels a bit too much for this small filter.
It also would make it difficult to perform another useful case: running pandoc inside docker. This would then require a privileged container and come with many other issues.

For the time being, you should probably build your container and run the filter inside it, instead of one container per code cell, e.g. something along these lines:

```Dockerfile
FROM pandoc/latex
RUN apt-get update && apt-get install python3-dev python3-pip && pip3 install pandoc-source-exec
WORKDIR /docs
CMD pandoc
```
and then running it as:
```sh
docker run -v $(pwd):/docs mypandoc pandoc -o ....
```

That should prevent your wrong cmd parameters sufficiently, and even allow you to build a docker image for your project to keep the dependencies clean.

**Comment by igormcoelho** [comment]
You are right, the safest solution is running all pandoc from docker.

Yet, I still feel that if maybe two binaries are available `pandoc-source-exec` and (maybe) `pandoc-docker-exec`, at this moment I would be using `pandoc-docker-exec`, and not using docker to protect my pandoc...
The reason is that I'm also trying to attract users for my tiny "ilectures tutorial", I need it to work on Linux, Mac, Windows, for average users (I'm quite far from that now) hahahah So, maybe if two binaries exist, "advanced users" could use `pandoc-docker-exec`, while those without docker could simply use `pandoc-source-exec`. 

Anyway, just an idea... your solution is fine enough for now.

**Comment by shoeffner** [comment]
You can also run 

    ```{ .sh .exec cmd='/Applications/Docker.app/Contents/Resources/bin/docker run --rm busybox' }
    ls
    ```

or whatever the docker path is on your system. But in general,  I would really suggest you do it the other way around.
